# Generated by Django 3.2.7 on 2021-09-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('autor', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('jurnal', 'jurnal'), ('gosip', 'gosip'), ('viral', 'viral')], default='gosip', max_length=25)),
            ],
        ),
    ]
